language: node_js
node_js:
  - "6"
addons:
  sauce_connect: true
matrix:
  fast_finish: true
before_install:
  - stty columns 120
install:
  - npm install
script:
  - npm run coverage
  - npm run codecov
  - npm run sauce
