language: node_js
node_js:
  - "6"
  - "7"
  - "8"
matrix:
  fast_finish: true
cache:
  yarn: true
  directories:
    - "node_modules"
before_install:
  - stty columns 120
install:
  - yarn --ignore-scripts
script:
  - npm run coverage
  - npm run codecov
